### ISSUE TITLE
R2modman isn’t recognizing the ModelReplacement mod

### ISSUE THREAD

**Issue by Hiderlink20** [TheSmallBlue/BRC-ModelReplacement#2]
I tried adding this mod to the game but I think bepin just ignores it.  R2modman doesn’t even detect it in my profile.  I don’t know how to get it to do so or how you’re supposed to import mods into R2Modman.

**Comment by Hiderlink20** [comment]
![Screenshot (53)](https://github.com/TheSmallBlue/BRC-ModelReplacement/assets/69734116/1d6385f6-b1e6-456b-b9cc-21a292f5efe9)
This is what I see.  I don't know what to do about this.

**Comment by TheSmallBlue** [comment]
the mod is r2modman compatible in the sense that when you press launch modded it will load up the game. it doesnt show up in the r2modman profile because it has none of the data r2modman uses to detect it. this is because r2modman's main focus is to download thunderstore mods, which do have this metadata, and since the mod isnt from thunderstore, it doesnt have it.
this will, most likely, never be fixed, since the mod's current design is based around people copying and pasting its assets instead of having them always downloaded, so having it on thunderstore makes no sense.
